export default [
  {
    id: 1,
    date: 'April 16th 2020',
    title: 'The Mountains',
    author: 'by John Appleseed',
    bgImage: 'mountains',
  },
  {
    id: 2,
    date: 'April 14th 2020',
    title: 'Sunset Cityscapes',
    author: 'by Benjamin Cruz',
    bgImage: 'city',
  },
  {
    id: 3,
    date: 'April 11th 2020',
    title: '18 Days Voyage',
    author: 'by Alexei Borodin',
    bgImage: 'voyage',
  },
  {
    id: 4,
    date: 'April 9th 2020',
    title: 'Architecturals',
    author: 'by Samantha Brooke',
    bgImage: 'architecturals',
  },
  {
    id: 5,
    date: 'April 7th 2020',
    title: 'World Tour 2019',
    author: 'by Timothy Wagner',
    bgImage: 'tour',
  },
  {
    id: 6,
    date: 'April 3rd 2020',
    title: 'Unforseen Corners',
    author: 'by William Malcolm',
    bgImage: 'corners',
  },
  {
    id: 7,
    date: 'March 29th 2020',
    title: 'King of Africa: Part II',
    author: 'by Tim Hillenburg',
    bgImage: 'africa',
  },
  {
    id: 8,
    date: 'March 21st 2020',
    title: 'The Trip to Nowhere',
    author: 'by Felice Rourke',
    bgImage: 'trip',
  },
  {
    id: 9,
    date: 'March 19th 2020',
    title: 'Rage of The Sea',
    author: 'by Mohammed Abdul',
    bgImage: 'sea',
  },
  {
    id: 10,
    date: 'March 16th 2020',
    title: 'Running Free',
    author: 'by Michelle',
    bgImage: 'run',
  },
  {
    id: 11,
    date: 'March 11th 2020',
    title: 'Behind the Waves',
    author: 'by Lamarr Wilson',
    bgImage: 'waves',
  },
  {
    id: 12,
    date: 'March 9th 2020',
    title: 'Calm Waters',
    author: 'by Samantha Brooke',
    bgImage: 'waters',
  },
  {
    id: 13,
    date: 'March 5th 2020',
    title: 'The Milky Way',
    author: 'by Benjamin Cruz',
    bgImage: 'milky',
  },
  {
    id: 14,
    date: 'March 4th 2020',
    title: 'Night at the Dark Forest',
    author: 'by Mohammed Abdul',
    bgImage: 'forest',
  },
  {
    id: 15,
    date: 'March 1st 2020',
    title: "Somwarpet's Beauty",
    author: 'by Michelle',
    bgImage: 'somwarpet',
  },
  {
    id: 16,
    date: 'February 25th 2020',
    title: 'Land of Dreams',
    author: 'by William Malcolm',
    bgImage: 'dreams',
  },
];
